### ISSUE TITLE
Create README.md based on a provided template

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/imvertor-lite#3]
Can we add an option like `--readme-template=README.md.template`  and add the result next to the generated schema file?

Template variables should include (see key; value is shown as example from boom.json):

- "scope": "public"
- "stereotype": "IMBOR-Objecttype"
- "author": "Arjen Brienen"
- "version": 1.0
- "created": "2018-10-02 09:57:43",  
- "modified": "2018-10-04 10:07:04"
-  "status": "Proposed"

The values are taken from the keys present on the root level of the class. Can we also find these for Amsterdam Schema?

**Comment by dariomory** [comment]
:wave: Below are two examples of the output generated in the latest version:

[boom.md (Enterprise Architect)](https://github.com/maykinmedia/imvertor-lite/files/6676919/boom.md)
[buurt.md (Amsterdam Schema)](https://github.com/maykinmedia/imvertor-lite/files/6676948/buurt.md)
